version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: sentistream-redis
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --save "" 
      --appendonly no 
      --maxmemory 200mb 
      --maxmemory-policy allkeys-lru
    networks:
      - sentistream-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: sentistream-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - sentistream-network

volumes:
  clickhouse-data:

networks:
  sentistream-network:
    driver: bridge
